version: 0.2

phases:
  build:
    commands:
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
      - docker build -t $ECR_REPO_NAME . 
      - docker tag $ECR_REPO_NAME:latest $AWS_ECR_URL/$ECR_REPO_NAME:latest
      - docker push $AWS_ECR_URL/$ECR_REPO_NAME:latest
